### PR TITLE
add a conf toggle so sponsors->prospectus in nav

### PR DESCRIPTION
**Pull request by phette23**
Sets the toggle to `true` so this takes effect right away. I debated if we should rename the menu link to "Prospectus" but I actually think it's better / clearer to leave it as "Sponsors", though that's debatable.

### CODE REVIEW

**Comment by triplingual** [comment]
@phette23 Is this PR moot at this point?

**Comment by phette23** [comment]
It's irrelevant for this year now but it'd be useful for future years. If you look at the progress of sponsorships:

1. We have no sponsors <--- useful here, /sponsors/ links to prospectus instead of an empty sponsors page
2. We have some sponsors — we want to show the sponsors page & it links to prospectus (current state)
3. We're no longer accepting sponsors — no need to link to prospectus, `site.data.conf.sponsor-buttons: false`

**Comment by triplingual** [comment]
Ah, understood. Would it be risky to merge it now? Do you want to wait until after the conference for any other reason?
Probably just my slightly compulsive but irregularly present desire for neatness kicking in.

**Comment by phette23** [comment]
I don't think there's any harm but I added a commit just now so `sponsors-links-to-prospectus` is false.

**Pull request merged**
