### PR TITLE
Add Posters

### PR DESCRIPTION
**Pull request by phette23**
This adds posters from [the spreadsheet here](https://docs.google.com/spreadsheets/d/1DA1Rki68xCzXPE2MaLHMHYjx-VETGm1w1y48D6_ysRU/edit#gid=243320611) to the site. To test:

- visit schedule day 2, posters event links to the /posters/ index
- list on /posters/ shows all 20 posters
- poster pages should show the correct title, speakers, and description

In the past, e.g. [2023](https://2023.code4lib.org/posters/), we did not add poster presenters to the speakers data nor show them on the speakers page so I didn't do that. There are two posters ("Automating File Organization by Leveraging Patterns with Python", "The Distant Reader") from folks who happen to also be giving talks and thus already in the speakers file, and their poster pages display differently due to this. That seems fine to me but I mention it in case you notice the inconsistency.

### CODE REVIEW

**Comment by triplingual** [comment]
There's some copyediting work on the titles to make them consistent, but I don't think that should hold up merging.

Somewhat more significant is the way the metadata on an individual abstract page has a superfluous yellow bar where the time goes for a full talk. Is there an easy way to suppress that?

**Comment by phette23** [comment]
@triplingual I saw the yellow bar but didn't think it was worth troubling over, it doesn't necessarily look info is missing just decorative. I thought about adding the length of the poster session (30 minutes) to all posters to have something show up there but that seemed like it might be misleading, you might mistake a poster page for a talk.

By copyediting, do you mean title case versus sentence case? That's the only thing I noticed after double-checking a few just now. We didn't use consistent case in talk titles, for what it's worth.

**Comment by phette23** [comment]
Looked to see if there's a liquid `title_case` filter but there isn't, that would have been really convenient.

**Review by escowles — APPROVED** [review]

**Comment by escowles** [comment]
I agree the empty yellow bar does look weird because I know there should be something there, but I don't think that's a big deal. Same with having a mix of title and sentence case for the poster titles — it didn't jump out to me looking at the page until I read the comments here.

**Review by escowles — APPROVED** [review]

**Pull request merged**
